### ISSUE TITLE
Final Todo list

### ISSUE THREAD

**Issue by dibaaamir** [Star-Academy/Summer1401-FE-Team01#7]
# API
- [x] get game with id 
- [x] list of wishlist games (get list, add to list ,remove from list)
- [x] list of purchased games (and date and price ...)
- [x] popular games ids
- [x] slideshow game ids
- [x] search and (filter optional)
- [x] categories

# UI/UX
- [x] fix search filters selected (in expansion list component) not being updated after navigating to search page from other pages (like clicking on a genre in game page)
- [x] profile page
- [x] bookmarks/favourites page
- [x] game page
- [x] search page
- [x] add page selection to games-grid component
- [x] add api to home page grid at bottom
- [ ] add rating range to search

## Optional
- [x] spinner for loadings
- [x] add bookmark and favourite button to search games-grid
- [ ] add stuff like genre,... to search games-grid
- [x] add bookmark and favourite button to search game-page
- [x] date persian
- [ ] game page have max height and "show more" button
- [ ] show multiple videos in game page
- [x] add price on sale to game page
- [x] add prices and release date to carousel
- [ ] responsive or not
